### ISSUE TITLE
Undefined method for non existing report 

### ISSUE THREAD

**Issue by DenniJensen** [cfb-hasenheide/cfb-hasenheide#105]
### Error [here](https://app.raygun.io/crashreporting/lw3i7r/errors/1605126538)
If no report exist for an event and it is requested a undefined Method will be thrown. This causes in the [reports controller](https://github.com/cfb-hasenheide/cfb-hasenheide/blob/master/app/controllers/reports_controller.rb#L24)

**Comment by DenniJensen** [comment]
@elgrillo83 is this fixed by https://github.com/cfb-hasenheide/cfb-hasenheide/commit/f03c6a93decb7241f7c2c1f916c62ba575c23dcc

**Comment by elgrillo83** [comment]
yes
