### ISSUE TITLE
Meldeliste öffnen - keine Mail versendet

### ISSUE THREAD

**Issue by hmutert** [cfb-hasenheide/cfb-hasenheide#108]
Moin,

Event Pokalspiel am Sonntag - habe jetzt mind. zweimal die Meldeliste mit Mail eröffnet. Geht aber keine Mail raus - keine Fehlermeldung.

haye

**Comment by hmutert** [comment]
![meldeliste](https://cloud.githubusercontent.com/assets/14013469/18312831/ea48b194-750b-11e6-9c38-e835bf68316b.png)

**Comment by elgrillo83** [comment]
@hmutert bug behoben, geht wieder.

@DenniJensen see: https://github.com/cfb-hasenheide/cfb-hasenheide/commit/ab7b3b4aca21e9ad9fd10f765bce36fa1561a328

**Comment by DenniJensen** [comment]
@elgrillo83 https://github.com/cfb-hasenheide/cfb-hasenheide/commit/9e54dfc9eabdd05c499e59d287f43093189644c7
