### ISSUE TITLE
Link zum Editieren des Spielberichts falsch

### ISSUE THREAD

**Issue by hmutert** [cfb-hasenheide/cfb-hasenheide#122]
URGENT!:: kann den Spielbericht nicht editieren, weil der Link falsch ist...

**Comment by hmutert** [comment]
@elgrillo83 
@DenniJensen 

beschleunigt dies die Sache?

**Comment by elgrillo83** [comment]
Nein, weil wir sowieso informiert werden. Ist gefixt.
