### ISSUE TITLE
handle redirect_to :back without HTTP referers

### ISSUE THREAD

**Issue by elgrillo83** [cfb-hasenheide/cfb-hasenheide#29]
add and use a redirect_back_or_to(path) method, see:

http://stackoverflow.com/questions/771656/correctly-doing-redirect-to-back-in-ruby-on-rails-when-referrer-is-not-availabl

**Comment by DenniJensen** [comment]
Cant find any `redirect_to :back`. Is this solved?

**Comment by elgrillo83** [comment]
Yes, for now there is no need for `redirect_to :back`
