### ISSUE TITLE
Spielerbilder

### ISSUE THREAD

**Issue by elgrillo83** [cfb-hasenheide/cfb-hasenheide#34]

**Comment by DenniJensen** [comment]
Uploading images for players? Is this issue about finding a solution to avoid carrywave or is it about trying to solve carrywave issues?

**Comment by elgrillo83** [comment]
This is about getting carrierwave to work with a new (club owned) AWS S3 account. I'm on it - together with Issue #31 where I want to implement bootsy as WYSIWYG editor with carrierwave support.

**Comment by DenniJensen** [comment]
Seems to work
