### ISSUE TITLE
Ämter / Beauftragte

### ISSUE THREAD

**Issue by elgrillo83** [cfb-hasenheide/cfb-hasenheide#35]
- Mitglieder halten 1-n Rollen im Verein inne
- Soll bei Mitglieder Anzeige angezeigt werden
- Mit History (Rolle von Datum bis Datum)

**Comment by DenniJensen** [comment]
Are roles used for more than one person? Can you assign **A** role for person and person **B** during the same time, or overlapping by time?

**Comment by DenniJensen** [comment]
@hmutert unter 'Administration' kannst du schonmal Rollen für den Verein anlegen und wenn erwünscht auch schon Personen für einen bestimmten Zeitraum zuweisen.


![image](https://cloud.githubusercontent.com/assets/3010752/18062238/feec5d72-6df3-11e6-825c-37eb8fd0196d.png)

Die Seite ist von der Benutzbarkeit nicht hundert Prozent. Aber wir wollten das Feature so schnell wie möglich bereitstellen.

Sollte es Probleme beim Erstellen oder Zuweisen geben, öffne bitte ein neues Issue mit der Problembeschreibung.


MFG.

Dennis
