### ISSUE TITLE
Fix Upcoming Events on Welcome Page

### ISSUE THREAD

**Issue by elgrillo83** [cfb-hasenheide/cfb-hasenheide#36]
Display the three next upcoming events asc

**Comment by elgrillo83** [comment]
Wasn't auto-closed by your commit?

**Comment by DenniJensen** [comment]
Review and merge it if everything is ok.

**Comment by hmutert** [comment]
Ich möchte gerne die nächsten drei Events sehen und dabei den kommenden zuerst.

**Comment by hmutert** [comment]
Und das finde ich eher wichtig, weil gerade zum Beispiel der Hasencup nicht angezeigt wird...

**Comment by hmutert** [comment]
Und das finde ich eher wichtig, weil gerade zum Beispiel das Pokalspiel nicht angezeigt wird und die Meldelisten-Mail nicht geht
