### ISSUE TITLE
Meldeliste closed after editing Event

### ISSUE THREAD

**Issue by hmutert** [cfb-hasenheide/cfb-hasenheide#42]
Wenn ich einen Event editiere (z.Bsp. den Ort ändere) wird die Meldeliste geschlossen und alle bisherigen Einträge gehen dabei verloren. Jederzeit reproduzierbar.

**Comment by elgrillo83** [comment]
Da haben wir wohl ein Problem in Richtung polymorphe Table (AttendanceList) und accepts_nested_attributes_for :attendance_list (Event). Shit. 

Siehe: http://stackoverflow.com/questions/3969025/accepts-nested-attributes-for-with-belongs-to-polymorphic
