### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by hmutert** [cfb-hasenheide/cfb-hasenheide#43]
![wrong](https://cloud.githubusercontent.com/assets/14013469/15702969/3cea1846-27e3-11e6-9c28-da54127fd126.png)

kommt immer, wenn

1. eine Meldung abgeben oder geändert wird - Aktion wird dennoch ausgeführt
2. die Meldeliste (mit/ohne Mail) eröffnet wird bei einem neu erstellten Event (Liga/Pokal/Sonstiges) . Aktion wird dennoch ausgeführt 
3. auch das Schliessen einer Meldeliste führt zu dem Fehler.

**Comment by DenniJensen** [comment]
Wird am Wochenende behoben. 
For dev: #42 #44 hängen alle zusammen.

**Comment by DenniJensen** [comment]
Is this fixed?
