### ISSUE TITLE
keine Aktualisierung der Empfängerliste in der Meldeliste

### ISSUE THREAD

**Issue by hmutert** [cfb-hasenheide/cfb-hasenheide#44]
Wenn ich die Empfängerliste beim Öffnen einer Meldeliste mit Mail bearbeite und mit "Fertig" bestätige, 
werden weiterhin alle default-Empfänger in der Empfänger-Aufzählung dargestellt.

![mailliste](https://cloud.githubusercontent.com/assets/14013469/15703403/524c87a8-27e5-11e6-900c-70fd3851f360.png)

**Comment by elgrillo83** [comment]
open_mail UND close_mail: nur checkboxen
