### ISSUE TITLE
Interne News anders darstellen

### ISSUE THREAD

**Issue by hmutert** [cfb-hasenheide/cfb-hasenheide#46]
Moin,

Interne News werden durch "Intern" in der News-Überschrift gekennzeichnet. Das sieht eher nicht soo toll aus. Wie wäre es mit einem kleinen Symbol oder noch besser, wäre eine farbliche Unterlegung (sanftes grün oder helles blau oder schwaches grau).

**Comment by hmutert** [comment]
soll das bedeuten, dass es jetzt anders gelöst ist ?
kann ich nicht erkennen...

**Comment by elgrillo83** [comment]
aktuell sind interne News grau und öffentlich News hasen-grün umrandet.
