### ISSUE TITLE
GoogleMaps Link für Events

### ISSUE THREAD

**Issue by elgrillo83** [cfb-hasenheide/cfb-hasenheide#53]
- soll durch die GoogleMaps Karte auf events#show repräsentiert werden
- soll als Link für den Ort in der Final Call Mail hinterlegt werden

**Comment by DenniJensen** [comment]
Remove Map and add the link from event#show?

**Comment by elgrillo83** [comment]
Ort und GoogleMaps Link separat in der DB speichern. Ort String anzeigen
und mit Maps Link unterlegen. Google Map mit der (genauen) Position aus dem
Link anzeigen.
