### ISSUE TITLE
Ergänzung Spieler-Profil

### ISSUE THREAD

**Issue by hmutert** [cfb-hasenheide/cfb-hasenheide#56]
Zwei zusätzliche Rubriken:
"Fußballerisches Vorbild" und "Mein persönlicher CFB-Moment"

**Comment by hmutert** [comment]
Im Spielerprofil sollte auch hinterlegt sein, zu welcher Mannschaft der Spieler gehört.
Dies sollte dann steuern, ob vom Spieler bei einem Event eine MEldung erwartet wird - entsprechend auch den Default-Mailverteiler bei Öffnen der Meldeliste.

Die drei bestehenden Optionen sind hier erstmal richtig.

**Comment by hmutert** [comment]
Das Spielerprofil sollte teilweise öffentlich sein. Welche Felder öffentlich sind und welche nur angemeldeten Usern angezeigt wird, müsste man noch mal definieren.

**Comment by elgrillo83** [comment]
- Add a questionnaire / profile
- Make certain fields of questionnaire / profile public
- Relate Teams and Players

**Comment by DenniJensen** [comment]
@hmutert haben wir aktuell mehr als ein Team?

**Comment by hmutert** [comment]
Im Moment haben wir nur ein Team. Generell möglich, dass ein Spiel für mehrere Teams gemeldet sein kann.

**Comment by hmutert** [comment]
Gut wäre auch, dass öffentliche Spielerphoto vom internen Avatar (Chat und so) zu unterscheiden, also Avatar zuzätzlich...

**Comment by DenniJensen** [comment]
@hmutert kannst du dazu bitte ein neues Issue ticket aufmachen? So haben wir zu jedem Wunsch ein Issue und können diese schneller und effizienter abarbeiten. Wenn zu viele Wünsche Anforderungen in einem Issue stecken, gehen diese oft verloren. 
Auch wenn wir schon mit dem Issue angefangen haben, ist es übersichtlicher wenn wir Issues durchsuchen, als in den Kommentaren nach weiteren Anforderung zu schauen.
