### ISSUE TITLE
chat

### ISSUE THREAD

**Issue by elgrillo83** [cfb-hasenheide/cfb-hasenheide#7]
preferable with the new cool kid in town 'action cable' (might not be working on heroku though)

**Comment by DenniJensen** [comment]
Is it necessary to keep the chat in the rails environment? Do you wish to try `Action Cable` or is it possible to create a chat as a microservice (e.g. ExpressJs)?

**Comment by elgrillo83** [comment]
Standalone would be great too. I imagine it to live on the subdomain chat.cfb.de but also with an integrated view on the Rails' main page for logged in users. Authorization must be implemented then. Language of choice.

**Comment by DenniJensen** [comment]
Faye on heroku: https://devcenter.heroku.com/articles/ruby-websockets

**Comment by hmutert** [comment]
Hat eigentlich schon mal jemand erwähnt, dass so ein Chat wirklich ne gute Sache wäre....

**Comment by hmutert** [comment]
Letztens sprachen mich einige Hasen an, ob es wohl möglich wäre, auf der neuen Seite auch wieder einen Chat anzubieten. Keine Ahnung, ob ihr Euch da schon Gedanken gemacht habt, aber das scheint mir eine gute Idee, weshalb ich es hier noch mal weitergebe...

**Comment by hmutert** [comment]
Der Chat scheint nicht zu funktionieren. Egal, was ich tippe, es wird nicht angezeigt, obwohl anscheinend jemand gerade vor 2 Minuten was in den Chat schreiben konnte...

**Comment by DenniJensen** [comment]
@elgrillo83 can we close this issue?

**Comment by elgrillo83** [comment]
A basic chat for text messages is done. Next steps in #84

**Comment by elgrillo83** [comment]
A basic chat for text messages is done. Next steps in #84

**Comment by hmutert** [comment]
funzt leider nicht mehr. Wenn ich was schreibe, kann ich es sehen, aber zwei Minuten später ist der EIntrag wieder verschwunden...

**Comment by elgrillo83** [comment]
ok @hmutert , schauen wir uns an!

**Comment by elgrillo83** [comment]
geht wieder @hmutert
