### ISSUE TITLE
Auto-create a Player after creating a User

### ISSUE THREAD

**Issue by elgrillo83** [cfb-hasenheide/cfb-hasenheide#73]
Currently there is a 500, because the default_url of the Player's avatar is tried to be rendered after signing up (creating a new User).

At the moment, I prefer a solution like:
- having an auto-created UserProfile, or store avatar_url and nickname/alias directly in Users table
- having a Member model with according fields
- and a Player model with according fields

**Comment by DenniJensen** [comment]
@elgrillo83 I will handle this. I notices same issue today. 
- I plan to structure things more on database level
  - creating clean relations between models
- build a chain of automated model creations when a new user is invided to the page
