### ISSUE TITLE
Remove action for user who are not allowed

### ISSUE THREAD

**Issue by DenniJensen** [cfb-hasenheide/cfb-hasenheide#97]
If user are not allow to do action, they do not need to see the button or the button must marked as disabled.
<img width="495" alt="screen shot 2016-08-30 at 17 23 29" src="https://cloud.githubusercontent.com/assets/3010752/18107602/90c24a1c-6ed6-11e6-80f5-a1f873c69a66.png">
### Checklist
- [x] Player edit
- [x] AttendanceList handling
- [x] Admin area

**Comment by elgrillo83** [comment]
This should be managed using access-granted.

**Comment by DenniJensen** [comment]
The the request handled or the view? I pointing just the view part, where the user get the information (NOT POSSIBLE) by disabling buttons

**Comment by elgrillo83** [comment]
Both ;-)

**Comment by DenniJensen** [comment]
@elgrillo83 can you show me the used gem, so I can dig into it and add some classes for the view elements.

**Comment by elgrillo83** [comment]
https://github.com/chaps-io/access-granted

something like:

access_policy.rb
```ruby
can [:open, :update], AttendanceList
```

```haml
view.haml
- if can? :open, AttendanceList
  render 'open_button'
- if can? :update, AttendanceList
  render 'edit_button'
```

**Comment by DenniJensen** [comment]
@elgrillo83 pls watch out for the usage of access-granted, for update you the the @instanze, this get passed the block in the policy
```haml
- if can? :update, @attendance_list
```
