### ISSUE TITLE
Add trainings

### ISSUE THREAD

**Issue by elgrillo83** [cfb-hasenheide/cfb-hasenheide#99]
Allow to manage which players attended which training sessions. Allow to define an additional_count for external training participants along with some information. Use a counter_cache to have a quick access to the overall count (e.g. on players#show).

- add trainings table
  - `date:date`
  - `additional_count:integer`
  - `additional_info:string`
- `:player` HABTM `:trainings`

**Comment by DenniJensen** [comment]
IMAO renmae
**training_attendances -> training_sessions** or **exercices**

I want get rid of the **attendances** subfix.

**Comment by elgrillo83** [comment]
attendances is not a suffix here, but as we discussed already, I'm not able to build it that way. the working solution is a pure HABTM between players and trainings.
